name: Tests for My Project

on: [push, pull_request]

jobs:
  test:
    name: Tests for My Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '23.1.1'
          elixir-version: '1.11.2'
      - name: Cache deps
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install hex
        run: |
          mix local.rebar --force
          mix local.hex --force
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix compile
      - name: Run Tests
        run: |
          mix test --trace
      - name: Check Formatted
        run: |
          mix format --check-formatted
      - name: Run Credo
        run: |
          mix credo --strict